name: Update Bluesky Posts JSON

on:
  schedule:
    - cron: '0 0 * * 1'  # Every hour at minute 0
  workflow_dispatch:      # Manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run export script
      env:
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: node exportBluesky.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sourcej.json
        git diff --cached --quiet || git commit -m "Update Bluesky posts JSON"
        git push
